prometheus-msteams/prometheus-msteams

alert/teams.go
Currently each event gets added as a section to a card so old alerts
are coming through again and again on new cards.
This bug can be replicated by taking the example test json and running
it back to back a few times. The first card will have 1 section, the
second two sections (1 duplicate), the third 3 sections (2 duplicates),
and so on.
Closes:#17
=> Fix duplication of sections across cards

default-message-card.tmpl, examples/templates/card-with-action.tmpl
Microsoft returns an error code when summary isn't defined.
This PR ensures that summary is defaulted to either message or alertname, in that order.
I generally add summary, but a lot of the default rules from the Prometheus Operator doesn't have summary.
Error response from MS API:
```
time="2019-04-04T21:41:15Z" level=info msg="Microsoft Teams response text: Summary or Text is required."
time="2019-04-04T21:41:15Z" level=error msg="Failed sending to the Teams Channel. Teams http response: 400 Bad Request"
```
=> Ensure summary is defined

alert/teams.go, alert/teams_test.go, go.mod
Fixes #54.
This might not be an indication that it is an array. Values starting with `[{` should be rather an indication for an array.
=> fix concatinating key-val pairs if the val starts with [

chart/README.md, chart/prometheus-msteams/templates/configMapTemplate.yaml, chart/prometheus-msteams/values.yaml
Edited the configMapTemplate.yaml to accept the message card template provided by the user through a value customCardTemplate.
=> Use custom cards with helm chart

chart/prometheus-msteams/Chart.yaml, chart/prometheus-msteams/templates/deployment.yaml
Hey, we wanna use the cahrt in Kubernetes 1.16 and your deployment still uses the deprecated api version which is to finally be removed. 
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Greetz Flowkap :)
=> Fix deprecated api which is incompatoble with Kubernetes > 1.16

examples/templates/card-with-silence-action.tmpl
The link for silencing an alert is hardcoded to `http://localhost:9093`. This should use the external URL value like elsewhere in the template.
=> Use external Url for the silence link

.travis.yml, Makefile
Would be nice to have MS Teams integration on Windows as well. I've compiled it on Linux and tested the binary on Windows 2019 and Windows 2012 R2.
=> Release Windows binaries

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, chart/prometheus-msteams/README.md, ct.yaml
Signed-off-by: Christian Kotzbauer <christian.kotzbauer@gmail.com>
This adds two github-actions for linting and testing on pull-requests and for publishing to github-pages. When this is merged and is working the repo on helm-hub should be updated.
Closes #149
=> Add initial helm-chart github-actions

chart/prometheus-msteams/Chart.yaml, chart/prometheus-msteams/card.tmpl, chart/prometheus-msteams/values.yaml
Sync the [repo's default card template](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/default-message-card.tmpl) with the chart's card template.
closes #154 .
=> fix helm chart default card template

chart/prometheus-msteams/Chart.yaml, chart/prometheus-msteams/card.tmpl, default-message-card.tmpl, pkg/card/templated_card_test.go, pkg/card/testdata/action-message-card.tmpl
See #156 for details.
* Added if statement to exclude "description" annotation to template (both chart and default).
* Incremented chart version.
* Adapted tests by removing "description" fact from expected results and adding if statement
to the template in test data.
=> Don't include "description" in "facts"

.gitignore, chart/prometheus-msteams/Chart.yaml, chart/prometheus-msteams/templates/deployment.yaml
Currently when the config of prometheus-msteams changes only the config map is updated and the pod is not restarted. The pod is still running with the old configuration then. Proposal by helm is to set an annotation to the pod that triggers a rollout restart in this case (see https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments). Like this the new configuration will be used by the new pod.
(added some IntellIJ Idea related gitignore settings)
=> Helm Chart: Automatically rollout restart pod when configmaps change

chart/prometheus-msteams/Chart.yaml, chart/prometheus-msteams/templates/servicemonitor.yaml
The `ServiceMonitor` definition states that the `targetPort` should "target the port of the Pod behind the Service"
```yaml
targetPort:
anyOf:
- type: integer
- type: string
description: Name or number of the target port of the Pod behind the Service, the port must be specified with container port property. Mutually exclusive with port.
x-kubernetes-int-or-string: true
```
=> Change ServiceMonitor `targetPort` to container's port

chart/prometheus-msteams/Chart.yaml, chart/prometheus-msteams/values.yaml
Otherwise helm will log:
```
coalesce.go:160: warning: skipped value for environment: Not a table.
```
when overriding this value.
See helm/helm#8283
=> make extraEnvs default value in helm an empty map

Dockerfile
Snyk reports vulnerabilities in alpine 3.9.5's openssl and musl installations.
Snyk on alpine 3.13 does not show any known vulnerabilities so far.
Vulnerability meta:
| ID | Package | Severity |
| --- | --- | --- |
| CVE-2020-1967 | openssl | high |
| CVE-2020-28928 | musl | medium |
=> Bump alpine version to 3.13

examples/templates/card-grafana-inspired.tmpl
As I also ran into the same issue described in #176, I wanted to contribute the fix.
This PR fixes the Alertmanger URL scheme in the example to enable correct filtering of alerts. The current URL configuration in the example leads to a not found page.
=> Fix Alertmanager URL scheme with filter

pkg/transport/transport.go
Hi,
the problem with of the panic is caused by the embedded pointer to *template.Data in webhook.Message (alertmanager)
https://github.com/prometheus/alertmanager/blob/v0.20.0/notify/webhook/webhook.go#L69
if template.Data is nil, all access to fields of template.Data will cause a panic. For example here:
https://github.com/prometheus-msteams/prometheus-msteams/blob/2c782049ccc0d4ea41338625f71ee279e6ffe004/pkg/card/templated_card.go#L60
Somewhere the application revers from panic. So maybe you want to keep it like it is?
fixes #209
=> added validation for incoming message (prevents panic)

Dockerfile
By default, Alpine Docker images don't include time zone data (see e.g. [here](https://www.stevejgordon.co.uk/timezonenotfoundexception-in-alpine-based-docker-images)). This results in e.g. the Sprig [`dateInZone`](http://masterminds.github.io/sprig/date.html) function to silently fall back to UTC because it can't look up the requested time zone on the system.
For example, the following call:
```gotmpl
{{- with index .Alerts 0 }}
{{ dateInZone "2006-01-02 15:04:05.00 MST" .StartsAt "CET" }}
{{- end }}
```
would fail to convert the start time of the alert to CET and just leave it in UTC.
Installing the [`tzdata`](https://pkgs.alpinelinux.org/package/edge/main/x86/tzdata) package in the Dockerfile fixes this problem.
The package adds just about 1.2 MB to the size of the Docker image.
=> Add tzdata package to Docker image

.github/workflows/release-chart.yaml, .github/workflows/release.yaml
This allows creating a release by pushing a tag to this repository.
This address partly #151 
More important this will allow maintainers to deploy releases easily #254
Actions
- renamed the release.yaml into release-chart.yaml
- created new release.yaml to build and test binaries and docker image
- a github release will be created if a tag (v*.*.*) is pushed
- all artifacts are automatically added
- release notes are generated by github
- tests are executed (make test) before upload
- docker image is started; if it does not exit within 2 minutes it's accepted as ok
- docker images will be published to registry. The following image tags are used:
- for tags: latest + version
- commits to master: master
=> new github-action release docker and binary

.github/workflows/golangci-lint.yaml, .golangci.yml, .travis.yml, Makefile
Hi @bzon, @Knappek,
This PR moves [golangci-lint](https://github.com/golangci/golangci-lint) from TravisCI to a native GHActions app, and also update it to the latest version.
NOTE: I´ve found a committed binary file too, which I am removing, as it seems to be a mistake for me. Let me know if I oversaw something.
=> Move golangci-lint from Travis to GH Actions

.github/workflows/golangci-lint.yaml
Go 1.18 is required in direct dependency [github.com/prometheus/alertmanager](https://github.com/prometheus/alertmanager/blob/2888649b473970400c0bd375fdd563486dc80481/go.mod#L1-L3) and indirect dependency [github.com/cenkalti/backoff/v4](https://github.com/cenkalti/backoff/blob/a04a6fe64ffb0e3fd0816460529d300be5f252df/go.mod#L1-L3).
> module github.com/prometheus/alertmanager
go 1.18
> module github.com/cenkalti/backoff/v4
go 1.18
Related to
#298 #301 #310
=> Use go 1.18 and latest golangci

chart/prometheus-msteams/README.md
Or else the helm command will fail with:
```txt
Error: "helm upgrade" requires 2 arguments
Usage:  helm upgrade [RELEASE] [CHART] [flags]
no such file or directory: prometheus-msteams/prometheus-msteams
```
=> Add missing backslash to helm upgrade command

.github/workflows/release-chart.yaml
Chart releaser action is failing since last release on every commit to master.
Don't know why. Maybe ignoring the issue is the way 🤷🏽
=> ci: skip helm chart upload if it already exists

README.md, cmd/server/main.go, cmd/server/main_test.go
This PR adds functionality to the `/_dynamicwebhook/` endpoint.
Currently the endpoint requires specifying the "Incoming Webhook" URL for MS Teams as part of the URL path.
The `receivers[].webhookConfigs[].url` is not considered a "secret"/"credential" field by Alertmanager in the same way as for example `receivers[].slackConfigs[].api_url` is. That means it won't be hidden from the config in the Web UI.
In order to support handling the Incoming Webhook URL like a secret credential we can rely on the `http_config` instead.
This PR adds support for specifying the Incoming Webhook URL in the `Authorization` header, with a bearer type of `webhook`.
Alertmanager will treat this as a credential and hide it from the Web UI.
=> Support authorization header

pkg/service/service.go
Force Content-Type header to JSON to resolve error:
>  {\"error\":{\"code\":\"InvalidRequestContent\",\"message\":\"The input body for trigger 'manual' of type 'Request' must be of type JSON, but was of type 'application/octet-stream'.\"}}
=> Force Content-Type to JSON for compatibility

chart/prometheus-msteams/templates/_helpers.tpl, chart/prometheus-msteams/templates/deployment.yaml, chart/prometheus-msteams/templates/serviceaccount.yaml, chart/prometheus-msteams/values.yaml
This PR implements the FEATURE #361 
User can now:
* create a service account and use it
* reference an existing service account
* us default service account
```yaml
serviceAccount:
create: false
annotations: {}
name: ""
serviceAccount:
create: true
annotations: {}
name: "some-sa-name"
serviceAccount:
create: false
annotations: {}
name: "existing-sa"
```
=> Allow user to create or refferrence different service accounts

README.md, cmd/server/main.go, cmd/server/main_test.go
Fixes #359
* Deprecated the old format (outlook.office.com)
* Updated the validating regex (`validate-webhook-url` flag) to support the current & new format
* Update README examples with the new pattern
=> Support new office connector url
