prometheus-msteams/prometheus-msteams

- .circleci/config.yml
- .gitignore
- Dockerfile
- Makefile
- alert/alert.go
- alert/alert_test.go
- alert/examples/prom_post_request.json
- alert/examples/teams_post_request.json
- cmd/root.go
- cmd/server.go
- main.go
Closes https://github.com/bzon/promteams/issues/1
* Renamed handler package to alert
* Added alert_test
* Refactored accordingly
* Updated Makefile and Dockerfile
* Updated repo name
> Add Unit Test and Refactor Code

- Dockerfile
- Makefile
- README.md
- alert/prom_handler.go
- alert/prom_handler_test.go
- alert/teams.go
* Enhanced testing of handlers
* Added PROMTEAMS_DEBUG variable to have the option to display json request received and created
* Make error handling right
> Refactor code

- cmd/server.go
> Fix misleading error message

- .gitignore
- Makefile
- alert/prom_handler.go
- alert/teams.go
- alert/teams_test.go
- alert/testdata/large_prom_post_request.json
- cmd/server.go
First draft to solve #29 .
Unit testing needs to be enhanced, but I'd like to have your input first. I have implemented to split a message that exceeds 14KB, because for some reason I got the error even with messages of size 15KB (although MS mentions somewhere 25KB as the limit).
> [issue-29] Chunk alerts when the request body is too large

- README.md
- alert/teams.go
- alert/teams_test.go
- alert/testdata/message-card-without-sections.tmpl
This avoids trapping into an endless loop, reported in #43 .
Still to do:
> [issue-43] avoid endless loop when trying to split message on key 'sections'

- .travis.yml
- README.md
- go.mod
Solves #64 . @bzon if it looks good to you, we can merge it.
> save the default card template along with binaries in releases

- chart/prometheus-msteams/Chart.yaml
- chart/prometheus-msteams/templates/configMapConfig.yaml
- chart/prometheus-msteams/templates/configMapTemplate.yaml
- chart/prometheus-msteams/templates/deployment.yaml
This is a small update for the chart
> Fix configMap names

- alert/teams.go
- default-message-card.tmpl
Log errors from json.Compact call for usability
> Enhance default-message-card.tmpl to prevent json parse errors

- chart/prometheus-msteams/templates/_helpers.tpl
- chart/prometheus-msteams/templates/deployment.yaml
> use deployment apiVersion based on k8s version

- alert/teams.go
- default-message-card.tmpl
This will help parsing the string returned by the template execution
> JSON escape all strings data in alertmanager notify.WebhookMessage

- README.md
Small change while tried to run the binary, the --help option helped to figure this one out. Just adding the right flag here
> corrected bash command for binary

- cmd/server/main.go
- go.sum
> Use the custom template file properly

- examples/templates/card-with-action.tmpl
- examples/templates/card-with-silence-action.tmpl
> fix example cards with actions due to invalid json

- cmd/server/main.go
closes #136 
@bzon do we also want to tackle #39?
> add version flag

- Makefile
> add windows to all target

- README.md
- chart/prometheus-msteams/Chart.yaml
- chart/prometheus-msteams/README.md
- chart/prometheus-msteams/values.yaml
> release v1.4.1

- README.md
- chart/prometheus-msteams/Chart.yaml
- chart/prometheus-msteams/templates/configMapConfig.yaml
- cmd/server/main.go
- e2e/e2e_test.go
- go.mod
- go.sum
- pkg/service/service.go
This adds wanted feature of issue #170.  It would be great if the reviewer could check config implementation as I was not too sure about that.
> added retry mechanism and made it configurable

- README.md
- cmd/server/main.go
- e2e/e2e_test.go
- pkg/transport/transport.go
This change allows to add a route handler which will generate a service based on the context of current request.
fixes #178
> added dynamic routes

- chart/prometheus-msteams/Chart.yaml
- chart/prometheus-msteams/templates/deployment.yaml
> fix helm template indentation for pod annotations

- README.md
- cmd/server/main.go
- cmd/server/main_test.go
- pkg/transport/transport.go
Hi,
I added validation to the _dynamicwebhhok.
BR
Kris
> validate webhook url (more secure)

- chart/prometheus-msteams/Chart.yaml
- chart/prometheus-msteams/templates/deployment.yaml
duplicates #195 in order to get it merged to master.
fixes #194
> Removing duplicated imagePullPolicy definition

- cmd/server/main.go
- pkg/testutils/testutils.go
> make it possible to disable validation of the server certificate

- chart/prometheus-msteams/Chart.yaml
- chart/prometheus-msteams/values.yaml
Removed default resources from helm chart - https://github.com/prometheus-msteams/prometheus-msteams/issues/271#issuecomment-1301047417
> feat: removed default resource chart values

- .github/workflows/trivy.yml
This will run every Wednesday a scan of the docker image produced by master.
Same as #286 but automated.
> added trivy scanner workflow action

- chart/prometheus-msteams/Chart.yaml
- chart/prometheus-msteams/values.yaml
new helm chart release
closes #315
> bumped helm chart / added maintainer

- cmd/server/main.go
This pull request intends to fix the issue described in #255.
Many thanks for your consideration.
Best regards,
Harald
> fix: use webhook instead of url for validation (#255)

- cmd/server/main.go
> disable debug logging by default
